defaults:
  - _self_
  - dataset: hf
  - model: vit-base-patch16-224
  - training: vit-base-oxford-iiit-pets
  - hydra: default

project: ??

run_name: ${now:%Y-%m-%d-%H-%M}

ckpt_dir: ./checkpoints/${project}

log:
  dir: ${ckpt_dir}/${run_name}/logs
  file: ${project}.log